services:
  - type: redis
    name: emotion-redis
    ipAllowList: []  # Allow access from all IPs; adjust as needed for security
  - type: web
    name: emotion-recognition-api
    runtime: python
    buildCommand: "cd Emotion-Backend && pip install -r requirements.txt"
    startCommand: "cd Emotion-Backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: "postgresql://emotion_data_user:ll0HxcVjbY2lBvyZ1wWqPXVs8JtOXPcd@dpg-d6iq67hdrdic73eigsrg-a/emotion_data"
      - key: MONGODB_URL
        value: "mongodb+srv://denzylibe04_db_user:XLR8*xlr8%26@emotion.qlircss.mongodb.net/emotion_recognition?retryWrites=true&w=majority&appName=Emotion"
      - key: MONGO_DATABASE
        value: "emotion_recognition"
      - key: REDIS_URL
        value: "rediss://default:AZ45AAIncDE2NWY4M2RhZmY5M2Y0ZTFlODg2ZmZiMzg0ODkzNmQwZHAxNDA1MDU@hip-dingo-40505.upstash.io:6379"
      - key: UPSTASH_REDIS_REST_URL
        value: "https://hip-dingo-40505.upstash.io"
      - key: UPSTASH_REDIS_REST_TOKEN
        value: "AZ45AAIncDE2NWY4M2RhZmY5M2Y0ZTFlODg2ZmZiMzg0ODkzNmQwZHAxNDA1MDU"
